name: Check & fix styling

on: [ push ]

jobs:
  styling:
    runs-on: ubuntu-latest

    env:
      NOVA_USERNAME: ${{ secrets.NOVA_USERNAME }}
      NOVA_PASSWORD: ${{ secrets.NOVA_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Install packages
        run: npm ci

      - name: Prettier
        run: npm run format

      - name: Lint
        run: npm run lint

      - name: Authenticate with Nova
        run: composer config http-basic.nova.laravel.com $NOVA_USERNAME $NOVA_PASSWORD

      - name: Install Composer dependencies
        run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader

      - name: Run Laravel Pint
        run: ./vendor/bin/pint

      - name: Run Rector
        run: ./vendor/bin/rector process
